# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basecloud', '0003_auto_20170312_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basecloud.SignUp'),
        ),
    ]
