# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basecloud', '0008_auto_20170314_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basecloud.SignUp'),
        ),
    ]
